### ISSUE TITLE
Add ability to not highlight toolbar button with new finished downloads

### ISSUE THREAD

**Issue by Infocatcher** [Infocatcher/Download_Panel_Tweaker#23]
This is from chrome://browser/skin/browser.css:

``` css
#downloads-button[attention] > #downloads-indicator-anchor > #downloads-indicator-icon {
  background-image: url("chrome://browser/skin/downloads/download-glow.png");
}
```

So, it's probably better to watch changes of this `attention` attribute. But in old Firefox version there is two downloads buttons...
