### ISSUE TITLE
Strange problem

### ISSUE THREAD

**Issue by happysurf** [Infocatcher/Download_Panel_Tweaker#53]
On last Firefox beta 51build2 i have this strange glitch on the panel. the description file text is missing:
Same problem is present also on Simple Addon Manager extension panel.

![glitch](https://cloud.githubusercontent.com/assets/13637587/20458110/47195482-ae9b-11e6-918e-4adbfcdd1407.png)

Test performed on two different PCs (windows 7):
E10s enabled + hardware acceleration: glitch;
E10s disabled hardware acceleration : glitch;
Hardware disabled on both : no glitch.

**Comment by Aris-t2** [comment]
I can confirm this. Happens for me too since Firefox 51 beta.

**Comment by Aris-t2** [comment]
Firefox 51 beta 2 fixed the problem.

The issue can be closed.

**Comment by Infocatcher** [comment]
Still buggy for me in Firefox 51 and 52 (looks fixed in Firefox 53+), but I found a workaround (<a href="http://kb.mozillazine.org/UserChrome.css">userChrome.css</a>):
```css
/*
Fix missing text and delays inside download panel in Firefox 51+
https://bugzilla.mozilla.org/show_bug.cgi?id=1318898
https://bugzilla.mozilla.org/show_bug.cgi?id=1306670
*/
#downloadsPanel description,
#downloadsPanel label {
	filter: brightness(1);
}
```
